name: Deploy to Production Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'viewer/package-lock.json'

      - name: Install Dependencies
        working-directory: viewer
        run: npm install

      - name: Build Project
        working-directory: viewer
        run: npm run build

      - name: Deploy to Server
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "viewer/dist/*"
          target: ${{ secrets.TARGET_DIR }}
          strip_components: 2